# Generated by Django 6.0.5 on 2026-07-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_updated_at_service_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
