# Generated by Django 6.0.5 on 2026-07-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(default='Box', max_length=100),
        ),
    ]
