# Generated by Django 6.0.5 on 2026-07-23 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesscards', '0001_initial'),
        ('products', '0002_product_icon'),
        ('services', '0004_alter_service_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='services',
            field=models.ManyToManyField(blank=True, to='services.service'),
        ),
        migrations.AlterField(
            model_name='businesscard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
